DROP TABLE IF EXISTS urls;
DROP TABLE IF EXISTS url_checks;

CREATE TABLE urls
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name       VARCHAR(255)                            NOT NULL,
    created_at TIMESTAMP,
    CONSTRAINT pk_url PRIMARY KEY (id)
);


CREATE TABLE url_checks
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    urlId       BIGINT                                  NOT NULL,
    statusCode  INT,
    title       VARCHAR(255),
    h1          VARCHAR(255),
    description VARCHAR(1024),
    created_at  TIMESTAMP,
    CONSTRAINT pk_url_checks PRIMARY KEY (id)
);
